### ISSUE TITLE
Migration on Scala 3

### ISSUE THREAD

**Issue by danicheg** [typelevel/monoids#219]
Currently, we are blocked on migration on Scala 3 due to a bug with `AnyVal`s: https://github.com/lampepfl/dotty/issues/11264
The obvious fix is dropping `AvyVal` for `Dual`, `Product` and `Sum`, but probably that will lead to performance issues.
Another [idea](https://github.com/typelevel/monoids/pull/147/files#r558808533) proposed by @ChristopherDavenport is using opaque types in Scala 3, and leave `AnyVal`s in Scala 2.

**Comment by danicheg** [comment]
@rossabaker it'd be great to release `monoids` on Scala 3 🙏🏻

**Comment by rossabaker** [comment]
I added the secrets so it can be released from ci with sbt-spiewak-sonatype or sbt-davenverse.
