### ISSUE TITLE
Migration on `typelevel` organization

### ISSUE THREAD

**Issue by danicheg** [typelevel/monoids#226]
Currently, we are `io.chrisdavenport` organization. 
A changing of an organization also means that would change the root package of the project. Obviously, that would lead to breaking compatibility. But I'm confident it's a necessary evil. What do you folks think about it?

**Comment by rossabaker** [comment]
I did this on unique, vault, keypool, and log4cats when they moved over.  And you're absolutely right: the package and the build organization need to change together.

This is probably worth discussing on Semigroups.  Bonus idea: do these really benefit from being separate projects, and, if not, isn't this an ideal time to revisit it?

**Comment by danicheg** [comment]
@rossabaker great, planning to do it after migration on Scala 3 then (#225).
 
Also, it's a good question why `semigroups` and `monoids` are separate libs. They have totally same structure and similar functionality. Moreover, their maintaining goes through the same steps (talking for myself - I did a few identically PRs to `monoids` and to `semigroups`). So I vote to `combine` them in one lib.
