### ISSUE TITLE
Combine `monoids` and `semigroups`

### ISSUE THREAD

**Issue by danicheg** [typelevel/monoids#232]
As @rossabaker suggested in #226 `monoids` and `semigroups` can be combined. I think we will get only benefits from it. They have totally same structure and similar functionality. Moreover, their maintaining goes through the same steps. What do you folks think about it?

**Comment by danicheg** [comment]
If we will unanimous in this combining I want it done after merging migration on Scala 3 https://github.com/typelevel/semigroups/pull/212.

**Comment by rossabaker** [comment]
I'm not using these yet, but I'll explain myself: they're separate libraries in Haskell, but `Semigroup` was added to `base` after `Monoid`, and became a superclass some time after that, so there's historical baggage that we don't have in Scala.  I can't think of another reason they'd be separate other than finding inspiration in Haskell, and the Typelevel repackaging is an ideal opportunity to merge them.
